// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pohezzjpibkpovbtjjka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvaGV6empwaWJrcG92YnRqamthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NzMzMDYsImV4cCI6MjA2ODQ0OTMwNn0.xtA-e35hZjzwPfpSLD5hc4CqiLCOrWJjWrtOP5SMBzY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});